version: 2

variables:
  test-documentable: &test-documentable
    run:
      name: Run tests
      command: |
        zef install .

        # test one build
        git clone https://github.com/antoniogamiz/mini-doc
        zef install https://github.com/antoniogamiz/Perl6-LinkHealth.git
        cd mini-doc
        documentable setup
        documentable start --topdir=test-doc -v -p -s --search-index -i
        linkhealth --html-dir=html

        # update option
        echo "dd" >> test-doc/Type/Any.pod6
        documentable update --topdir=test-doc

        # build docs
        cd ..
        git checkout docs-assets
        git checkout master -- docs
        documentable start --topdir=docs -v -a --highlight --highlight-path="/highlights"
jobs:
  test-linux:
    docker:
      - image: antoniogamiz/documentable
    steps:
      - checkout
      - *test-documentable
      - persist_to_workspace:
          root: ./
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "antoniogamiz@gmail.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "8a:fb:97:e9:33:14:74:35:85:65:33:f5:34:22:7c:37"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist ./html
workflows:
  version: 2
  test:
    jobs:
      - test-linux
      - docs-deploy:
          requires:
            - test-linux
          filters:
            branches:
              only: master
